baseURL: "https://home.erronliu.top"
languageCode: "zh-CN"
title: "Weleen Words"
contentDir: "./content"
publicDir: "./public"
theme: "PaperMod"

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"

menus:
  main:
  - name: "Home"
    pageRef: "/"
    weight: 10
  - name: "随便玩玩"
    pageRef: "/series/随便玩玩"
    weight: 20
  - name: "编程杂谈"
    pageRef: "/series/编程杂谈"
    weight: 30

params:
  profileMode:
    enabled: true
    titie: "Weleen Words"
    subtitle: "Always Up Here."
    imageUrl: "https://erronliu-typora-picgo.oss-cn-hangzhou.aliyuncs.com/uploaded/EscapeII21835_square2560.jpg"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: "Blogs"
        url: "/blog"
  socialIcons:
    - name: "github"
      url: "https://github.com/ErronZrz"
  ShowBreadCrumbs: true
  ShowToc: true
  ShowCodeCopyButtons: true
