baseURL: https://erronliu.top/home/
languageCode: zh-CN
title: Weleen Words
contentDir: ./content
publicDir: ./public
theme: PaperMod

params:
  profileMode:
    enabled: true
    titie: "Weleen Words"
    subtitle: "Always Up Here."
    imageUrl: "https://erronliu-typora-picgo.oss-cn-hangzhou.aliyuncs.com/uploaded/Escape%20II21835_square2560.jpg"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Pages
        url: "/home/blog"
  socialIcons:
    - name: "github"
      url: "https://github.com/ErronZrz"
  ShowBreadCrumbs: true
  ShowToc: true
  ShowCodeCopyButtons: true
